#!/bin/sh
test -e $HOME/.fbb && . $HOME/.fbb

test -z "$BROWSER" && BROWSER=links
if test "$BROWSER" = links && test -z "$BROWSER_ARGS"
then
	BROWSER_ARGS=-g
fi

for i in "$@"
do
	"$BROWSER" $BROWSER_ARGS "$i"
done
