#!/bin/sh
if test ! -e ~/.minecraft/versions/btw
then
	echo 'create: .minecraft/versions/btw'
	cd ~/.minecraft/versions/
	mkdir btw
	cp -r 1.5.2/1.5.2.json btw/btw.json
	cd btw
	sed -i '/^  "id":/s/1.5.2/btw/' btw.json
fi
install-btw-server.sh $1 || exit 1
install-btw-client.sh $1 || exit 1
