#!/bin/sh

elder() {
	sed 's/(th)/ᚦ/g;
	     s/(ae)/ᛇ/g;
	     s/(ng)/ᛜ/g;
	     y/fuþarkgwhnijpïzstbemlŋdo/ᚠᚢᚦᚨᚱᚲᚷᚹᚺᚾᛁᛃᛈᛇᛉᛊᛏᛒᛖᛗᛚᛜᛞᛟ/'
}

long() {
	sed 's/(th)/ᚦ/g;
	     y/fuþoąrkhniastbmlR/ᚠᚢᚦᚬᚬᚱᚴᚼᚾᛁᛅᛋᛏᛒᛘᛚᛦ/'
}

short() {
	sed 's/(th)/ᚦ/g;
	     y/fuþoąrkhniastbmlR/ᚠᚢᚦᚭᚭᚱᚴᚽᚿᛁᛆᛌᛐᛓᛙᛚᛧ/'
}

medieval() {
	sed 's/(dh)/ᚧ/g;
	     s/(th)/ᚦ/g;
	     s/(ae)/ᛅ/g;
	     s/(oe)/ᚯ/g;
	     y/abcdðefghiklmnopqrstuvwxyzþäæöø/ᛆᛒᛍᛑᚧᛂᚠᚵᚼᛁᚴᛚᛘᚿᚮᛔᛩᚱᛋᛐᚢᚡᚥᛪᛦᛎᚦᛅᛅᚯᚯ/'
}

punctuation() {
	sed 's/\. */᛫/g;
	     s/ /᛬/g'
}

usage() {
	echo "usage: runify [elder|long|short|medieval]" 1>&2
	exit 1
}

if test $# -gt 1; then usage; fi
if test $# -eq 0; then set -- elder; fi

case "$1" in
	elder|long|short|medieval) punctuation | $1;;
	*) usage;;
esac
