#!/bin/sh
elder() {
	sed 's/(th)/ᚦ/g;
	s/(ae)/ᛇ/g;
	s/(ng)/ᛜ/g;
	y/fuþarkgwhnijpïzstbemlŋdo/ᚠᚢᚦᚨᚱᚲᚷᚹᚺᚾᛁᛃᛈᛇᛉᛊᛏᛒᛖᛗᛚᛜᛞᛟ/'
}

long() {
	sed 's/(th)/ᚦ/g;
	y/fuþoąrkhniastbmlR/ᚠᚢᚦᚬᚬᚱᚴᚼᚾᛁᛅᛋᛏᛒᛘᛚᛦ/'
}

short() {
	sed 's/(th)/ᚦ/g;
	y/fuþoąrkhniastbmlR/ᚠᚢᚦᚭᚭᚱᚴᚽᚿᛁᛆᛌᛐᛓᛙᛚᛧ/'
}
medieval() {
	sed 's/(dh)/ᚧ/g;
	     s/(th)/ᚦ/g;
	     s/(ae)/ᛅ/g;
	     s/(oe)/ᚯ/g;
	     y/abcdðefghiklmnopqrstuvwxyzþäæöø/ᛆᛒᛍᛑᚧᛂᚠᚵᚼᛁᚴᛚᛘᚿᚮᛔᛩᚱᛋᛐᚢᚡᚥᛪᛦᛎᚦᛅᛅᚯᚯ/'
}
punctuation() {
	sed 's/\. */᛫/g;
	s/ /᛬/g'
}

if test $# -eq 0
then
	punctuation | elder
else
	if test $# -eq 1
	then
		case "$1" in
			elder)
				punctuation | elder
				;;
			long)
				punctuation | long
				;;
			short)
				punctuation | short
				;;
			medieval)
				punctuation | medieval
				;;
			*)
				echo "Recognized runic alphabets: elder, long, short, medieval" 1>&2
				exit 1
				;;
		esac
	else
		echo "Usage: $(basename "$0") [elder | long | short | medieval]" 1>&2
		exit 1
	fi
fi
