#!/bin/sh
elder() {
	sed 's/(th)/ᚦ/g;
	s/(ae)/ᛇ/g;
	s/(ng)/ᛜ/g;
	s/f/ᚠ/g;
	s/u/ᚢ/g;
	s/þ/ᚦ/g;
	s/a/ᚨ/g;
	s/r/ᚱ/g;
	s/k/ᚲ/g;
	s/g/ᚷ/g;
	s/w/ᚹ/g;
	s/h/ᚺ/g;
	s/n/ᚾ/g;
	s/i/ᛁ/g;
	s/j/ᛃ/g;
	s/p/ᛈ/g;
	s/ï/ᛇ/g;
	s/z/ᛉ/g;
	s/s/ᛊ/g;
	s/t/ᛏ/g;
	s/b/ᛒ/g;
	s/e/ᛖ/g;
	s/m/ᛗ/g;
	s/l/ᛚ/g;
	s/ŋ/ᛜ/g;
	s/d/ᛞ/g;
	s/o/ᛟ/g'
}

long() {
	sed 's/(th)/ᚦ/g;
	s/f/ᚠ/g;
	s/u/ᚢ/g;
	s/þ/ᚦ/g;
	s/o/ᚬ/g;
	s/r/ᚱ/g;
	s/k/ᚴ/g;
	s/h/ᚼ/g;
	s/n/ᚾ/g;
	s/i/ᛁ/g;
	s/a/ᛅ/g;
	s/s/ᛋ/g;
	s/t/ᛏ/g;
	s/b/ᛒ/g;
	s/m/ᛘ/g;
	s/l/ᛚ/g;
	s/R/ᛦ/g;'
}

short() {
	sed 's/(th)/ᚦ/g;
	s/f/ᚠ/g;
	s/u/ᚢ/g;
	s/þ/ᚦ/g;
	s/o/ᚭ/g;
	s/r/ᚱ/g;
	s/k/ᚴ/g;
	s/h/ᚽ/g;
	s/n/ᚿ/g;
	s/i/ᛁ/g;
	s/a/ᛆ/g;
	s/s/ᛌ/g;
	s/t/ᛐ/g;
	s/b/ᛓ/g;
	s/m/ᛙ/g;
	s/l/ᛚ/g;
	s/R/ᛧ/g;'
}
punctuation() {
	sed 's/\. */᛫/g;
	s/ /᛬/g'
}

if test $# -eq 0
then
	punctuation | elder
else
	if test $# -eq 1
	then
		case "$1" in
			elder)
				punctuation | elder
				;;
			long)
				punctuation | long
				;;
			short)
				punctuation | short
				;;
			*)
				echo "Recognized runic alphabets: elder, long, short" 1>&2
				exit 1
				;;
		esac
	else
		echo "Usage: $(basename "$0") [elder | long | short]" 1>&2
		exit 1
	fi
fi
