#!/bin/sh
test -e $HOME/.vidplay && . $HOME/.vidplay

if test -z "$VIDPLAYER" && test -z "$VIDPLAYER_ARGS"
then
	test -z "$MPVO" && MPVO=xv
	VIDPLAYER=mplayer
	VIDPLAYER_ARGS="-vo $MPVO -framedrop -vfm ffmpeg -lavdopts fast:skiploopfilter=all"
fi

"$VIDPLAYER" $VIDPLAYER_ARGS "$@"
