#!/bin/sh
test -e $HOME/.vidplay && . $HOME/.vidplay

if test -z "$VIDPLAYER" && test -z "$VIDPLAYER_ARGS"
then
	test -z "$MPVO" && MPVO=gl
	VIDPLAYER=mplayer
	VIDPLAYER_ARGS="-vo $MPVO -framedrop"
fi

"$VIDPLAYER" $VIDPLAYER_ARGS "$@"
