#!/bin/sh
test -e $HOME/.vidplay && . $HOME/.vidplay

test -z "$MPVO" && MPVO=gl
test -z "$VIDPLAYER" && VIDPLAYER=mplayer

if test "$VIDPLAYER" = mplayer && test -z "$VIDPLAYER_ARGS"
then
	VIDPLAYER_ARGS="-vo $MPVO -framedrop"
fi

"$VIDPLAYER" $VIDPLAYER_ARGS "$@"
